title: NanoLocz User Guide
description: A guide for using NanoLocz
baseurl: "/NanoLocz/docs" # Adjust if needed based on the repository name and path
url: "https://George-R-Heath.github.io" # Your GitHub Pages URL
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
