title: NanoLocz User Guide
description: A guide for using NanoLocz
baseurl: "/NanoLocz/docs" # Adjust if needed based on the repository name and path
url: "https://George-R-Heath.github.io" # Your GitHub Pages URL
theme: minima
markdown: kramdown
